import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface EarResult {
  level: number;
  frequency: string;
  result: 'pass' | 'refer';
}

export interface ReportData {
  childName: string;
  age: string;
  schoolName: string;
  className: string;
  testDate: string;
  leftEarResults: EarResult[];
  rightEarResults: EarResult[];
  overallResult: 'pass' | 'refer';
  conductedBy: string;
}

export function generateHearWiseReport(data: ReportData): void {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header background (teal)
  doc.setFillColor(13, 148, 136);
  doc.rect(0, 0, pageWidth, 40, 'F');

  // Company name
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('HearWise Technologies', 14, 18);

  // Subtitle
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('India\'s First School Hearing Screening Platform', 14, 26);
  doc.text('hearwise.in | support@hearwise.in', 14, 32);

  // Report title
  doc.setTextColor(13, 148, 136);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Child Hearing Screening Report', 14, 54);

  // Divider
  doc.setDrawColor(13, 148, 136);
  doc.setLineWidth(0.5);
  doc.line(14, 57, pageWidth - 14, 57);

  // Child details section
  doc.setTextColor(30, 30, 30);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Child Information', 14, 66);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  const details = [
    ['Child Name', data.childName],
    ['Age', data.age],
    ['School', data.schoolName],
    ['Class', data.className],
    ['Test Date', data.testDate],
    ['Screened By', data.conductedBy],
  ];
  details.forEach(([label, value], i) => {
    doc.setFont('helvetica', 'bold');
    doc.text(`${label}:`, 14, 74 + i * 7);
    doc.setFont('helvetica', 'normal');
    doc.text(value, 55, 74 + i * 7);
  });

  // Overall result badge
  const resultColor = data.overallResult === 'pass' ? [22, 163, 74] : [220, 38, 38];
  doc.setFillColor(resultColor[0], resultColor[1], resultColor[2]);
  doc.roundedRect(pageWidth - 60, 62, 46, 18, 3, 3, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  const resultText = data.overallResult === 'pass' ? '✓ PASS' : '⚠ REFER';
  doc.text(resultText, pageWidth - 50, 73);

  // Left Ear Results Table
  doc.setTextColor(30, 30, 30);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Left Ear Results', 14, 122);

  autoTable(doc, {
    startY: 126,
    head: [['Level', 'Frequency', 'Result']],
    body: data.leftEarResults.map(r => [
      `Level ${r.level}`,
      r.frequency,
      r.result.toUpperCase()
    ]),
    headStyles: { fillColor: [13, 148, 136], textColor: 255 },
    bodyStyles: { fontSize: 9 },
    alternateRowStyles: { fillColor: [240, 253, 250] },
    columnStyles: {
      2: {
        fontStyle: 'bold'
      }
    },
    didParseCell: (data) => {
      if (data.section === 'body' && data.column.index === 2) {
        data.cell.styles.textColor = data.cell.raw === 'PASS' ? [22, 163, 74] : [220, 38, 38];
      }
    },
    margin: { left: 14, right: pageWidth / 2 + 4 },
  });

  // Right Ear Results Table
  doc.setFont('helvetica', 'bold');
  doc.text('Right Ear Results', pageWidth / 2 + 4, 122);

  autoTable(doc, {
    startY: 126,
    head: [['Level', 'Frequency', 'Result']],
    body: data.rightEarResults.map(r => [
      `Level ${r.level}`,
      r.frequency,
      r.result.toUpperCase()
    ]),
    headStyles: { fillColor: [13, 148, 136], textColor: 255 },
    bodyStyles: { fontSize: 9 },
    alternateRowStyles: { fillColor: [240, 253, 250] },
    margin: { left: pageWidth / 2 + 4, right: 14 },
  });

  // Recommendation box
  const finalY = (doc as any).lastAutoTable.finalY + 12;
  doc.setFillColor(data.overallResult === 'pass' ? 240 : 254, data.overallResult === 'pass' ? 253 : 242, data.overallResult === 'pass' ? 250 : 242);
  doc.roundedRect(14, finalY, pageWidth - 28, 28, 3, 3, 'F');
  doc.setTextColor(30, 30, 30);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('Recommendation:', 18, finalY + 8);
  doc.setFont('helvetica', 'normal');
  const recommendation = data.overallResult === 'pass'
    ? 'This child has passed the HearWise screening. No immediate follow-up is required. Re-screen annually.'
    : 'This child has been flagged for further evaluation. Please consult a qualified audiologist at the earliest. Early intervention significantly improves outcomes.';
  const splitRec = doc.splitTextToSize(recommendation, pageWidth - 40);
  doc.text(splitRec, 18, finalY + 15);

  // Footer
  doc.setFillColor(245, 247, 250);
  doc.rect(0, 277, pageWidth, 20, 'F');
  doc.setTextColor(150, 150, 150);
  doc.setFontSize(7);
  doc.text('This report is generated by HearWise Technologies. It is a screening tool and not a clinical diagnosis.', 14, 284);
  doc.text('For clinical diagnosis, please consult a licensed audiologist. | hearwise.in', 14, 289);

  // Save
  const fileName = `HearWise_Report_${data.childName.replace(/\s+/g, '_')}_${data.testDate.replace(/\//g, '-')}.pdf`;
  doc.save(fileName);
}
